### ISSUE TITLE
Remove uni_links from the project

### ISSUE THREAD

**Issue by mkobuolys** [crowdin/flutter-sdk#49]
The https://pub.dev/packages/uni_links package is almost deprecated - the last update was published 2 years ago. Since it is a transitive dependency in the crowdin-sdk, it causes some issues. E.g. for Android, apps cannot be migrated to Gradle 8.4. Are there any plans to remove this package and replace it with an alternative?

**Comment by andrii-bodnar** [comment]
Hi @mkobuolys, thanks for the suggestion!

Are there any good alternatives to the `uni_links` package?

**Comment by mkobuolys** [comment]
> Hi @mkobuolys, thanks for the suggestion!
> 
> Are there any good alternatives to the `uni_links` package?

Well, I am not entirely sure what are you using this package for, but:
a) Maybe you do not need to use any package at all and can handle custom deep links using a router, but...
b) ... I assume you do not have any router in the package (since it's not UI-related). https://pub.dev/packages/app_links looks like an alternative for it.
c) If you only use this package for a specific task, it should not hurt much to maintain this part yourself by implementing the native portion of the code.

**Comment by andrii-bodnar** [comment]
As I can see, it is only used in the [crowdin_oauth.dart](https://github.com/crowdin/flutter-sdk/blob/main/lib/src/real_time_preview/crowdin_oauth.dart) module.

The methods used are `parse`, `uriLinkStream.listen`:

https://github.com/crowdin/flutter-sdk/blob/619fb3ee8afd816a50d81e22d41bb818b681ee0d/lib/src/real_time_preview/crowdin_oauth.dart#L22-L47

**Comment by mkobuolys** [comment]
`Uri.parse` is a standard Dart core method, so you should take care of `uriLinkStream.listen`. It seems that you only need to be notified about deep links happening on the native side. Having this in mind, app_links should work (https://pub.dev/packages/app_links#applinks-usage). I think developers (or QA after the change) just need to verify whether the same information is provided, and you should be good to go.
