### ISSUE TITLE
Usage with other i18n packages

### ISSUE THREAD

**Issue by mcosti** [crowdin/flutter-sdk#58]
**Is your feature request related to a problem? Please describe.**
An already existing codebase that is currently using easy_localization with json files

**Describe the solution you'd like**
Would be great if the package would take care of the authentication/caching for other i18n solutions, like easy_localization.

Example here: https://github.com/aissat/easy_localization_loader/blob/master/lib/src/http_asset_loader.dart

**Comment by andrii-bodnar** [comment]
Hi @mcosti!

In the example provided, you can use the Distributions CDN endpoints to get the translations.

See the [For Web Applications](https://support.crowdin.com/content-delivery/#for-web-applications) section for more details.

Please let me know if this makes sense for your use case.
