### ISSUE TITLE
LateError (LateInitializationError: Field 'previewArb' has not been initialized.)

### ISSUE THREAD

**Issue by abdulrahumanea** [crowdin/flutter-sdk#59]
I am trying to integrate crowdin sdk to my flutter project for Over The Air Content Delivery. Getting error LateError (LateInitializationError: Field 'previewArb' has not been initialized.). when we ran the application. Followed every step, nothing missed to my knowledge. Please help on this

If I need to step back to previous version please inform

1. Just follow the steps described in https://github.com/crowdin/flutter-sdk, including real time preview
2. Run the application in VSCode. Run -> Start Debugging
3. It will ask for OAuth authorisation
4. Immediately after returning to our app, this crash occurs

- Crowdin Flutter SDK: crowdin_sdk: ^0.6.3
- Flutter version: Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 13.6 22G120 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.91.0)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Nithya’s iPhone. Ensure the device is unlocked and attached with a
      cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
- Dart version: Dart SDK version: 3.4.3 (stable) (Tue Jun 4 19:51:39 2024 +0000) on "macos_arm64"

 - Device: iPhone X
 - OS: iOS 16.7.8

**Comment by andrii-bodnar** [comment]
Hi @abdulrahumanea,

Could you please confirm that the issue is reproducible on the [example project](https://github.com/crowdin/flutter-sdk/tree/main/example)? Thank you!

**Comment by abdulrahumanea** [comment]
which crowdin sdk version i need to use. 

downloaded the example project
changed 

  # In your real app use:
  #   crowdin_sdk: x.x.x
  crowdin_sdk:
    path: ../

to

  crowdin_sdk: ^0.6.3

getting below issue

[example] flutter pub get --no-example
"ar": 1 untranslated message(s).
"es": 1 untranslated message(s).
"es_US": 1 untranslated message(s).
"he": 1 untranslated message(s).
"hi": 1 untranslated message(s).
"it": 1 untranslated message(s).
"ja": 1 untranslated message(s).
"uk": 1 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 


This will generate a JSON format file containing all messages that 
need to be translated.
Resolving dependencies...
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because example depends on flutter_localizations from sdk which depends on intl 0.19.0, intl 0.19.0 is required.
So, because example depends on intl >=0.17.0 <0.19.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Try upgrading your constraint on intl: flutter pub add intl:^0.19.0
exit code 1

--

[example] flutter pub get --no-example
Resolving dependencies...
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because example depends on flutter_localizations from sdk which depends on intl 0.19.0, intl 0.19.0 is required.
So, because example depends on intl >=0.17.0 <0.19.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Try upgrading your constraint on intl: flutter pub add intl:^0.19.0
exit code 1

**Comment by andrii-bodnar** [comment]
@abdulrahumanea could you please use the [Formatting Syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) to highlight the code and structure the message? It's hard to understand this. Thanks a lot!

**Comment by abdulrahumanea** [comment]
working fine with example project, will check my app in detail and get back to you

**Comment by abdulrahumanea** [comment]
it will work with GetMaterialApp too, right?

**Comment by abdulrahumanea** [comment]
try change example app with GetMaterialApp, that too is working fine
can you give me a hind why this error is happening then?

**Comment by andrii-bodnar** [comment]
@FlutterOd do you have any ideas?

**Comment by abdulrahumanea** [comment]
i have put the project [here](https://github.com/abdulrahumanea/crowdin_briive.git). Can you verify

**Comment by abdulrahumanea** [comment]
did anyone check? did got the error? please update

**Comment by andrii-bodnar** [comment]
@abdulrahumanea checking, we will update you

**Comment by abdulrahumanea** [comment]
i have been continuously following up on this issue for the past few days. This issue is creating a block for our app development. So I would request you to either fix the issue or suggest me a solution.
We would also like to know what the exact issue is. We have been using crowdin for the past few years.
Waiting for your response at the earliest.

**Comment by andrii-bodnar** [comment]
@abdulrahumanea We are still investigating the issue and have not found out what is causing this. Sorry for the inconvenience.

**Comment by FlutterOd** [comment]
Hi @abdulrahumanea 

Real time preview requires the translation to be loaded from Crowdin .

Please try using the `Crowdin.loadTranslations(locale)` method in some initial steps of your project (see Crowdin example project). It should solve the problem

**Comment by abdulrahumanea** [comment]
yea, that was the issue
